// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iPath.EF.Core.Database;

#nullable disable

namespace iPath.EF.Sqlite.Migrations
{
    [DbContext(typeof(iPathDbContext))]
    [Migration("20251203132129_Notifications2e")]
    partial class Notifications2e
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("NOCASE")
                .HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_on");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_on");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipath2_id");

                    b.HasKey("Id")
                        .HasName("pk_annotations");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_annotations_node_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_annotations_owner_id");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visibility");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipath2_id");

                    b.HasKey("Id")
                        .HasName("pk_communities");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_communities_owner_id");

                    b.ToTable("communities", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.CommunityGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("community_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.HasKey("Id")
                        .HasName("pk_community_group");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_community_group_community_id");

                    b.HasIndex("GroupId", "CommunityId")
                        .IsUnique()
                        .HasDatabaseName("ix_community_group_group_id_community_id");

                    b.ToTable("community_group", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.CommunityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("AllGroups")
                        .HasColumnType("INTEGER")
                        .HasColumnName("all_groups");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("community_id");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int?>("iPath2_Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("i_path2_id");

                    b.HasKey("Id")
                        .HasName("pk_community_member");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_community_member_community_id");

                    b.HasIndex("UserId", "CommunityId")
                        .IsUnique()
                        .HasDatabaseName("ix_community_member_user_id_community_id");

                    b.ToTable("community_member", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("receiver");

                    b.Property<DateTime?>("SentOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("sent_on");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_temp_emails");

                    b.ToTable("temp_emails", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_date");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_name");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("object_id");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("object_name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("EventId")
                        .HasName("pk_eventstore");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("ix_eventstore_event_date");

                    b.HasIndex("EventName")
                        .HasDatabaseName("ix_eventstore_event_name");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_eventstore_object_id");

                    b.HasIndex("ObjectName")
                        .HasDatabaseName("ix_eventstore_object_name");

                    b.ToTable("eventstore", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_on");

                    b.Property<int>("GroupType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_type");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<string>("StorageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_id");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visibility");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipath2_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_groups_owner_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_favourite");

                    b.Property<int>("NotificationSource")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notification_source");

                    b.Property<int>("NotificationTarget")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notification_target");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_group_members");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_members_group_id");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_members_user_id_group_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_on");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_draft");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("node_type");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_node_id");

                    b.Property<Guid?>("RootNodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("root_node_id");

                    b.Property<int?>("SortNr")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_nr");

                    b.Property<string>("StorageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipath2_id");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_nodes_group_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_nodes_owner_id");

                    b.HasIndex("RootNodeId")
                        .HasDatabaseName("ix_nodes_root_node_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_nodes_user_id");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.NodeImport", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT")
                        .HasColumnName("info");

                    b.HasKey("NodeId")
                        .HasName("pk_node_imports");

                    b.ToTable("node_imports", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.NodeLastVisit", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.HasKey("UserId", "NodeId")
                        .HasName("pk_node_lastvisits");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_node_lastvisits_date");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_lastvisits_node_id");

                    b.ToTable("node_lastvisits", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<bool>("DailySummary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_summary");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_on");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_queue");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_queue_user_id");

                    b.ToTable("notification_queue", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_on");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<string>("QuestionnaireId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("questionnaire_id");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_questionnaires");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_questionnaires_owner_id");

                    b.HasIndex("QuestionnaireId", "IsActive")
                        .HasDatabaseName("ix_questionnaires_questionnaire_id_is_active");

                    b.HasIndex("QuestionnaireId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_questionnaires_questionnaire_id_version");

                    b.ToTable("questionnaires", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireForGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("ExplicitVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("explicit_version");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("TEXT")
                        .HasColumnName("questionnaire_id");

                    b.Property<int>("Usage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage");

                    b.HasKey("Id")
                        .HasName("pk_questionnaire_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_questionnaire_groups_group_id");

                    b.HasIndex("QuestionnaireId")
                        .HasDatabaseName("ix_questionnaire_groups_questionnaire_id");

                    b.ToTable("questionnaire_groups", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnnotationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("annotation_id");

                    b.Property<Guid?>("AnnotationId1")
                        .HasColumnType("TEXT")
                        .HasColumnName("annotation_id1");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_on");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_on");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<Guid?>("NodeId1")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id1");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("TEXT")
                        .HasColumnName("questionnaire_id");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource");

                    b.HasKey("Id")
                        .HasName("pk_questionnaire_responses");

                    b.HasIndex("AnnotationId")
                        .HasDatabaseName("ix_questionnaire_responses_annotation_id");

                    b.HasIndex("AnnotationId1")
                        .HasDatabaseName("ix_questionnaire_responses_annotation_id1");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_questionnaire_responses_node_id");

                    b.HasIndex("NodeId1")
                        .HasDatabaseName("ix_questionnaire_responses_node_id1");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_questionnaire_responses_owner_id");

                    b.HasIndex("QuestionnaireId")
                        .HasDatabaseName("ix_questionnaire_responses_questionnaire_id");

                    b.ToTable("questionnaire_responses", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("lockout_end");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipath2_id");

                    b.Property<string>("ipath2_password")
                        .HasColumnType("TEXT")
                        .HasColumnName("ipath2_password");

                    b.Property<string>("ipath2_username")
                        .HasColumnType("TEXT")
                        .HasColumnName("ipath2_username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Annotation", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Node", "Node")
                        .WithMany("Annotations")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_annotations_nodes_node_id");

                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_annotations_users_owner_id");

                    b.Navigation("Node");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Community", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_communities_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iPath.Domain.Entities.CommunityGroup", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Community", "Community")
                        .WithMany("Groups")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_group_communities_community_id");

                    b.HasOne("iPath.Domain.Entities.Group", "Group")
                        .WithMany("Communities")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_group_groups_group_id");

                    b.Navigation("Community");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("iPath.Domain.Entities.CommunityMember", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_community_member_communities_community_id");

                    b.HasOne("iPath.Domain.Entities.User", "User")
                        .WithMany("CommunityMembership")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_member_users_user_id");

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Group", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("fk_groups_users_owner_id");

                    b.OwnsOne("iPath.Domain.Entities.GroupSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("GroupId");

                            b1.Property<bool>("AnnotationsHide");

                            b1.Property<bool>("DescriptionAllowHtml");

                            b1.Property<string>("DescriptionTemplate")
                                .IsRequired();

                            b1.Property<string>("Purpose")
                                .IsRequired();

                            b1.HasKey("GroupId");

                            b1.ToTable("groups");

                            b1.ToJson("settings");

                            b1.WithOwner()
                                .HasForeignKey("GroupId")
                                .HasConstraintName("fk_groups_groups_id");
                        });

                    b.Navigation("Owner");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("iPath.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("iPath.Domain.Entities.User", "User")
                        .WithMany("GroupMembership")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_user_id");

                    b.OwnsOne("iPath.Domain.Entities.NotificationSettings", "NotificationSettings", b1 =>
                        {
                            b1.Property<Guid>("GroupMemberId");

                            b1.Property<bool>("DailyEmailSummary");

                            b1.Property<string>("IcdoTopoCode");

                            b1.Property<TimeOnly?>("SummaryEmailTime");

                            b1.HasKey("GroupMemberId");

                            b1.ToTable("group_members");

                            b1.ToJson("notification_settings");

                            b1.WithOwner()
                                .HasForeignKey("GroupMemberId")
                                .HasConstraintName("fk_group_members_group_members_id");
                        });

                    b.Navigation("Group");

                    b.Navigation("NotificationSettings");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Node", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Group", "Group")
                        .WithMany("Nodes")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("fk_nodes_groups_group_id");

                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nodes_users_owner_id");

                    b.HasOne("iPath.Domain.Entities.Node", "RootNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("RootNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_nodes_nodes_root_node_id");

                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany("OwnedNodes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_nodes_users_user_id");

                    b.OwnsOne("iPath.Domain.Entities.NodeDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("NodeId");

                            b1.Property<string>("AccessionNo");

                            b1.Property<string>("CaseType");

                            b1.Property<string>("Status");

                            b1.Property<string>("Subtitle");

                            b1.Property<string>("Text");

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.HasKey("NodeId");

                            b1.ToTable("nodes");

                            b1.ToJson("description");

                            b1.WithOwner()
                                .HasForeignKey("NodeId")
                                .HasConstraintName("fk_nodes_nodes_id");
                        });

                    b.OwnsOne("iPath.Domain.Entities.NodeFile", "File", b1 =>
                        {
                            b1.Property<Guid>("NodeId");

                            b1.Property<string>("Filename");

                            b1.Property<int?>("ImageHeight");

                            b1.Property<int?>("ImageWidth");

                            b1.Property<DateTime?>("LastStorageExportDate");

                            b1.Property<string>("MimeType");

                            b1.Property<string>("ThumbData");

                            b1.HasKey("NodeId");

                            b1.ToTable("nodes");

                            b1.ToJson("file");

                            b1.WithOwner()
                                .HasForeignKey("NodeId")
                                .HasConstraintName("fk_nodes_nodes_id");
                        });

                    b.Navigation("Description");

                    b.Navigation("File");

                    b.Navigation("Group");

                    b.Navigation("Owner");

                    b.Navigation("RootNode");
                });

            modelBuilder.Entity("iPath.Domain.Entities.NodeLastVisit", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Node", "Node")
                        .WithMany("LastVisits")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_lastvisits_nodes_node_id");

                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany("NodeVisitis")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_lastvisits_users_user_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Notification", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_queue_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Questionnaire", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaires_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireForGroup", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Group", "Group")
                        .WithMany("Quesionnaires")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_groups_groups_group_id");

                    b.HasOne("iPath.Domain.Entities.Questionnaire", "Questionnaire")
                        .WithMany("Groups")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_groups_questionnaires_questionnaire_id");

                    b.Navigation("Group");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireResponse", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Annotation", "Annotation")
                        .WithMany()
                        .HasForeignKey("AnnotationId")
                        .HasConstraintName("fk_questionnaire_responses_annotations_annotation_id");

                    b.HasOne("iPath.Domain.Entities.Annotation", null)
                        .WithMany("QuestionnaireResponses")
                        .HasForeignKey("AnnotationId1")
                        .HasConstraintName("fk_questionnaire_responses_annotations_annotation_id1");

                    b.HasOne("iPath.Domain.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .HasConstraintName("fk_questionnaire_responses_nodes_node_id");

                    b.HasOne("iPath.Domain.Entities.Node", null)
                        .WithMany("QuestionnaireResponses")
                        .HasForeignKey("NodeId1")
                        .HasConstraintName("fk_questionnaire_responses_nodes_node_id1");

                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_responses_users_owner_id");

                    b.HasOne("iPath.Domain.Entities.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_responses_questionnaires_questionnaire_id");

                    b.Navigation("Annotation");

                    b.Navigation("Node");

                    b.Navigation("Owner");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("iPath.Domain.Entities.User", b =>
                {
                    b.OwnsOne("iPath.Domain.Entities.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Email");

                            b1.Property<string>("FamilyName")
                                .HasMaxLength(50)
                                .HasJsonPropertyName("familyname");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(50)
                                .HasJsonPropertyName("firstname");

                            b1.Property<string>("Initials")
                                .HasMaxLength(3)
                                .HasJsonPropertyName("initials");

                            b1.Property<string>("Specialisation")
                                .HasJsonPropertyName("specialisation");

                            b1.Property<string>("Username");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.ToJson("profile");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");

                            b1.OwnsOne("iPath.Domain.Entities.ContactDetails", "ContactDetails", b2 =>
                                {
                                    b2.Property<Guid>("UserProfileUserId");

                                    b2.Property<string>("Email");

                                    b2.Property<string>("Organisation");

                                    b2.Property<string>("PhoneNr");

                                    b2.HasKey("UserProfileUserId");

                                    b2.ToTable("users");

                                    b2.ToJson("profile");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfileUserId")
                                        .HasConstraintName("fk_users_users_user_profile_user_id");

                                    b2.OwnsOne("iPath.Domain.Entities.Address", "Address", b3 =>
                                        {
                                            b3.Property<Guid>("ContactDetailsUserProfileUserId");

                                            b3.Property<string>("City");

                                            b3.Property<string>("Country");

                                            b3.Property<string>("PostalCode");

                                            b3.Property<string>("Street");

                                            b3.HasKey("ContactDetailsUserProfileUserId");

                                            b3.ToTable("users");

                                            b3.ToJson("profile");

                                            b3.WithOwner()
                                                .HasForeignKey("ContactDetailsUserProfileUserId")
                                                .HasConstraintName("fk_users_users_contact_details_user_profile_user_id");
                                        });

                                    b2.Navigation("Address")
                                        .IsRequired();
                                });

                            b1.Navigation("ContactDetails")
                                .IsRequired();
                        });

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("iPath.Domain.Entities.Annotation", b =>
                {
                    b.Navigation("QuestionnaireResponses");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Community", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Group", b =>
                {
                    b.Navigation("Communities");

                    b.Navigation("Members");

                    b.Navigation("Nodes");

                    b.Navigation("Quesionnaires");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Node", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("ChildNodes");

                    b.Navigation("LastVisits");

                    b.Navigation("QuestionnaireResponses");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Questionnaire", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("iPath.Domain.Entities.User", b =>
                {
                    b.Navigation("CommunityMembership");

                    b.Navigation("GroupMembership");

                    b.Navigation("NodeVisitis");

                    b.Navigation("OwnedNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
