// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iPath.EF.Core.Database;

#nullable disable

namespace iPath.Database.Sqlite.Migrations
{
    [DbContext(typeof(iPathDbContext))]
    [Migration("20260113100613_UserFkUpdates")]
    partial class UserFkUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("NOCASE")
                .HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChildNodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Data", "iPath.Domain.Entities.Annotation.Data#AnnotationData", b1 =>
                        {
                            b1.Property<string>("Text");

                            b1.Property<int>("Type");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Morphology", "iPath.Domain.Entities.Annotation.Data#AnnotationData.Morphology#CodedConcept", b2 =>
                                {
                                    b2.Property<string>("Code")
                                        .IsRequired();

                                    b2.Property<string>("Display")
                                        .IsRequired();

                                    b2.Property<string>("System")
                                        .IsRequired();
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Questionnaire", "iPath.Domain.Entities.Annotation.Data#AnnotationData.Questionnaire#QuestionnaireResponseData", b2 =>
                                {
                                    b2.Property<string>("QuestionnaireId")
                                        .IsRequired();

                                    b2.Property<string>("Resource")
                                        .IsRequired();

                                    b2.Property<int?>("Version");
                                });

                            b1.ToJson("Data");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ChildNodeId");

                    b.HasIndex("NodeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "iPath.Domain.Entities.Community.Settings#CommunitySettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BaseUrl");

                            b1.PrimitiveCollection<string>("CaseTypes")
                                .IsRequired();

                            b1.Property<string>("Description");

                            b1.Property<bool>("DescriptionAllowHtml");

                            b1.Property<string>("DescriptionTemplate")
                                .IsRequired();

                            b1.ToJson("Settings");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("communities", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.CommunityGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("community_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("GroupId", "CommunityId")
                        .IsUnique();

                    b.ToTable("community_groups", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.CommunityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("AllGroups")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("community_id");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int?>("iPath2_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId", "CommunityId")
                        .IsUnique();

                    b.ToTable("community_group_members", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("temp_emails", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("EventDate");

                    b.HasIndex("EventName");

                    b.HasIndex("ObjectId");

                    b.HasIndex("ObjectName");

                    b.ToTable("eventstore", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "iPath.Domain.Entities.Group.Settings#GroupSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("AllowedAnnotationTypes")
                                .IsRequired();

                            b1.Property<bool>("AnnotationHasMoprhoogy");

                            b1.Property<bool>("AnnotationsHide");

                            b1.PrimitiveCollection<string>("CaseTypes")
                                .IsRequired();

                            b1.Property<bool>("DescriptionAllowHtml");

                            b1.Property<bool>("DescriptionGroupedBodySiteInput");

                            b1.Property<string>("DescriptionTemplate")
                                .IsRequired();

                            b1.Property<bool>("DescriptionWithBodySite");

                            b1.Property<string>("Purpose")
                                .IsRequired();

                            b1.Property<bool>("UseCaseSubTitleField");

                            b1.Property<bool>("UseCaseTitleField");

                            b1.Property<bool>("UseCaseTypeField");

                            b1.ToJson("Settings");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NotificationSettings", "iPath.Domain.Entities.GroupMember.NotificationSettings#NotificationSettings", b1 =>
                        {
                            b1.Property<bool>("DailyEmailSummary");

                            b1.Property<string>("IcdoTopoCode");

                            b1.Property<TimeOnly?>("SummaryEmailTime");

                            b1.ToJson("NotificationSettings");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RootNodeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SortNr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Description", "iPath.Domain.Entities.Node.Description#NodeDescription", b1 =>
                        {
                            b1.Property<string>("AccessionNo");

                            b1.Property<string>("CaseType");

                            b1.Property<string>("Status");

                            b1.Property<string>("Subtitle");

                            b1.Property<string>("Text");

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "BodySite", "iPath.Domain.Entities.Node.Description#NodeDescription.BodySite#CodedConcept", b2 =>
                                {
                                    b2.Property<string>("Code")
                                        .IsRequired();

                                    b2.Property<string>("Display")
                                        .IsRequired();

                                    b2.Property<string>("System")
                                        .IsRequired();
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Questionnaire", "iPath.Domain.Entities.Node.Description#NodeDescription.Questionnaire#QuestionnaireResponseData", b2 =>
                                {
                                    b2.Property<string>("QuestionnaireId")
                                        .IsRequired();

                                    b2.Property<string>("Resource")
                                        .IsRequired();

                                    b2.Property<int?>("Version");
                                });

                            b1.ToJson("description");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "File", "iPath.Domain.Entities.Node.File#NodeFile", b1 =>
                        {
                            b1.Property<string>("Filename");

                            b1.Property<int?>("ImageHeight");

                            b1.Property<int?>("ImageWidth");

                            b1.Property<DateTime?>("LastStorageExportDate");

                            b1.Property<string>("MimeType");

                            b1.Property<string>("ThumbData");

                            b1.ToJson("file");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RootNodeId");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.NodeImport", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.HasKey("NodeId");

                    b.ToTable("NodeImports");
                });

            modelBuilder.Entity("iPath.Domain.Entities.NodeLastVisit", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "NodeId");

                    b.HasIndex("Date");

                    b.HasIndex("NodeId");

                    b.ToTable("node_lastvisits", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DailySummary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionnaireId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("QuestionnaireId", "IsActive");

                    b.HasIndex("QuestionnaireId", "Version")
                        .IsUnique();

                    b.ToTable("questionnaires", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireForGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("ExplicitVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Usage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("questionnaire_groups", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireResponseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnnotationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationId");

                    b.HasIndex("NodeId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("questionnaire_responses", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("iPath.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ipath2_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipath2_password")
                        .HasColumnType("TEXT");

                    b.Property<string>("ipath2_username")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Profile", "iPath.Domain.Entities.User.Profile#UserProfile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("EmailAddress");

                            b1.Property<string>("FamilyName")
                                .HasMaxLength(50);

                            b1.Property<string>("FirstName")
                                .HasMaxLength(50);

                            b1.Property<string>("Initials")
                                .HasMaxLength(3);

                            b1.Property<string>("Specialisation");

                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Username");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "ContactDetails", "iPath.Domain.Entities.User.Profile#UserProfile.ContactDetails#ContactDetails", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Email");

                                    b2.Property<string>("Organisation");

                                    b2.Property<string>("PhoneNr");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Address", "iPath.Domain.Entities.User.Profile#UserProfile.ContactDetails#ContactDetails.Address#Address", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("City");

                                            b3.Property<string>("Country");

                                            b3.Property<string>("PostalCode");

                                            b3.Property<string>("Street");
                                        });
                                });

                            b1.ToJson("profile");
                        });

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("iPath.Domain.Entities.Annotation", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Node", "ChildNode")
                        .WithMany()
                        .HasForeignKey("ChildNodeId");

                    b.HasOne("iPath.Domain.Entities.Node", "Node")
                        .WithMany("Annotations")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildNode");

                    b.Navigation("Node");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Community", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iPath.Domain.Entities.CommunityGroup", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Community", "Community")
                        .WithMany("Groups")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iPath.Domain.Entities.Group", "Group")
                        .WithMany("Communities")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("iPath.Domain.Entities.CommunityMember", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("iPath.Domain.Entities.User", "User")
                        .WithMany("CommunityMembership")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Group", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iPath.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iPath.Domain.Entities.User", "User")
                        .WithMany("GroupMembership")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Node", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Group", "Group")
                        .WithMany("Nodes")
                        .HasForeignKey("GroupId");

                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany("OwnedNodes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("iPath.Domain.Entities.Node", "RootNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("RootNodeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Group");

                    b.Navigation("Owner");

                    b.Navigation("RootNode");
                });

            modelBuilder.Entity("iPath.Domain.Entities.NodeLastVisit", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Node", "Node")
                        .WithMany("LastVisits")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("iPath.Domain.Entities.User", "User")
                        .WithMany("NodeVisitis")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Notification", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireEntity", b =>
                {
                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireForGroup", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Group", "Group")
                        .WithMany("Quesionnaires")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iPath.Domain.Entities.QuestionnaireEntity", "Questionnaire")
                        .WithMany("Groups")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireResponseEntity", b =>
                {
                    b.HasOne("iPath.Domain.Entities.Annotation", "Annotation")
                        .WithMany("QuestionnaireResponses")
                        .HasForeignKey("AnnotationId");

                    b.HasOne("iPath.Domain.Entities.Node", "Node")
                        .WithMany("QuestionnaireResponses")
                        .HasForeignKey("NodeId");

                    b.HasOne("iPath.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("iPath.Domain.Entities.QuestionnaireEntity", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotation");

                    b.Navigation("Node");

                    b.Navigation("Owner");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Annotation", b =>
                {
                    b.Navigation("QuestionnaireResponses");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Community", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Group", b =>
                {
                    b.Navigation("Communities");

                    b.Navigation("Members");

                    b.Navigation("Nodes");

                    b.Navigation("Quesionnaires");
                });

            modelBuilder.Entity("iPath.Domain.Entities.Node", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("ChildNodes");

                    b.Navigation("LastVisits");

                    b.Navigation("QuestionnaireResponses");
                });

            modelBuilder.Entity("iPath.Domain.Entities.QuestionnaireEntity", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("iPath.Domain.Entities.User", b =>
                {
                    b.Navigation("CommunityMembership");

                    b.Navigation("GroupMembership");

                    b.Navigation("NodeVisitis");

                    b.Navigation("OwnedNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
